# rocker/geospatial is way to heavy. couldn't get r-devel to behave.
# so went with r-ci (https://github.com/eddelbuettel/r-ci).

kind: pipeline
name: r-ci (light)

steps:
- name: build 'n check
  image: rocker/r-bspm:20.04
  commands:
  - wget https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh
  - ./run.sh bootstrap
  - apt-get install -y --no-install-recommends libgeos-dev
  - ./run.sh install_deps
  - ./run.sh install_r wk  # needed since binary package of 'wk' still too old
  - export _R_CHECK_FORCE_SUGGESTS_="false"; ./run.sh run_tests

#---
# takes more than twice the time of light

#kind: pipeline
#name: r-ci (full)
#
#steps:
#- name: build 'n check
#  image: rocker/r-bspm:20.04
#  commands:
#  - wget https://eddelbuettel.github.io/r-ci/run.sh && chmod 0755 run.sh
#  - export ADDED_PPAS="ppa:ubuntugis/ppa"
#  - export BOOTSTRAP_LATEX="true"
#  - export R_BUILD_ARGS=""
#  - export R_CHECK_ARGS="--as-cran"
#  - ./run.sh bootstrap
#  - ./run.sh install_all
#  - apt-get install -y --no-install-recommends libgeos-dev
#  - export _R_CHECK_FORCE_SUGGESTS_="true"; ./run.sh run_tests
