# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

geos_version <- function() {
    .Call(`_apcf_geos_version`)
}

pcf_envelope <- function(sim, dist, ratio, rs, area, nobj, stoyan, nrank) {
    .Call(`_apcf_pcf_envelope`, sim, dist, ratio, rs, area, nobj, stoyan, nrank)
}

rand_dists_ratios_wkb <- function(wkb_pattern, wkb_area, max_dist, n_simulations = 99L, max_tries = 100000L, save_randomized_pattern = FALSE, verbose = FALSE) {
    .Call(`_apcf_rand_dists_ratios_wkb`, wkb_pattern, wkb_area, max_dist, n_simulations, max_tries, save_randomized_pattern, verbose)
}

